const fs = require('fs');
const path = require('path');

const CHARACTERS_FILE = path.join(__dirname, 'data', 'characters.ts');
const MOVES_FILE = path.join(__dirname, 'data', 'moves.ts');

const newCharacters = `
	crimsonassassin: {
		num: 7,
		name: "Crimson Assassin",
		types: ["Shadow", "Dragon"],
		baseStats: { hp: 310, atk: 140, def: 60, spa: 50, spd: 65, spe: 130 },
		abilities: {0: "Swift Step"},
		weightkg: 60,
	},
	tidalshaman: {
		num: 8,
		name: "Tidal Shaman",
		types: ["Nature", "Arcane"],
		baseStats: { hp: 380, atk: 60, def: 85, spa: 110, spd: 120, spe: 80 },
		abilities: {0: "Arcane Mastery"},
		weightkg: 65,
	},
	ironsentinel: {
		num: 9,
		name: "Iron Sentinel",
		types: ["Holy"],
		baseStats: { hp: 450, atk: 90, def: 150, spa: 60, spd: 110, spe: 40 },
		abilities: {0: "Thick Hide"},
		weightkg: 400,
	},
	voidwalker: {
		num: 10,
		name: "Void Walker",
		types: ["Undead", "Shadow"],
		baseStats: { hp: 500, atk: 110, def: 90, spa: 100, spd: 90, spe: 50 },
		abilities: {0: "Berserker"},
		weightkg: 85,
	},
	astralweaver: {
		num: 11,
		name: "Astral Weaver",
		types: ["Arcane"],
		baseStats: { hp: 280, atk: 40, def: 70, spa: 150, spd: 85, spe: 115 },
		abilities: {0: "Arcane Mastery"},
		weightkg: 45,
	},
	stormdrake: {
		num: 12,
		name: "Storm Drake",
		types: ["Dragon", "Nature"],
		baseStats: { hp: 350, atk: 125, def: 85, spa: 105, spd: 85, spe: 100 },
		abilities: {0: "Thick Hide"},
		weightkg: 210,
	},
`;

const newMovesStr = `
	crimsonblade: {
		num: 101,
		accuracy: 100,
		basePower: 95,
		category: "Physical",
		name: "Crimson Blade",
		pp: 15,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "High critical hit ratio.",
		target: "normal",
		type: "Shadow",
	},
	holybash: {
		num: 102,
		accuracy: 100,
		basePower: 80,
		category: "Physical",
		name: "Holy Bash",
		pp: 20,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "30% chance to make the target flinch.",
		target: "normal",
		type: "Holy",
		secondary: {
			chance: 30,
			volatileStatus: 'flinch',
		},
	},
	dragonsweep: {
		num: 103,
		accuracy: 90,
		basePower: 110,
		category: "Physical",
		name: "Dragon Sweep",
		pp: 10,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "Hits all adjacent foes.",
		target: "allAdjacentFoes",
		type: "Dragon",
	},
	naturefang: {
		num: 104,
		accuracy: 100,
		basePower: 75,
		category: "Physical",
		name: "Nature Fang",
		pp: 15,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "Heals 50% of the damage dealt.",
		target: "normal",
		type: "Nature",
		drain: [1, 2],
	},
	undeadstrike: {
		num: 105,
		accuracy: 100,
		basePower: 120,
		category: "Physical",
		name: "Undead Strike",
		pp: 15,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "User takes 33% recoil damage.",
		target: "normal",
		type: "Undead",
		recoil: [33, 100],
	},
	arcaneedge: {
		num: 106,
		accuracy: true,
		basePower: 90,
		category: "Physical",
		name: "Arcane Edge",
		pp: 15,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "This move does not check accuracy.",
		target: "normal",
		type: "Arcane",
	},
	voidcrush: {
		num: 107,
		accuracy: 90,
		basePower: 100,
		category: "Physical",
		name: "Void Crush",
		pp: 10,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "20% chance to lower target's Defense by 1.",
		target: "normal",
		type: "Undead",
		secondary: {
			chance: 20,
			boosts: {
				def: -1,
			},
		},
	},
	ironfist: {
		num: 108,
		accuracy: 100,
		basePower: 85,
		category: "Physical",
		name: "Iron Fist",
		pp: 15,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "Power doubles if user moves after the target.",
		target: "normal",
		type: "Holy",
	},
	quickslash: {
		num: 109,
		accuracy: 100,
		basePower: 40,
		category: "Physical",
		name: "Quick Slash",
		pp: 30,
		priority: 1,
		flags: { protect: 1, mirror: 1, contact: 1 },
		shortDesc: "Usually goes first.",
		target: "normal",
		type: "Shadow",
	},
	savagebite: {
		num: 110,
		accuracy: 95,
		basePower: 65,
		category: "Physical",
		name: "Savage Bite",
		pp: 15,
		priority: 0,
		flags: { protect: 1, mirror: 1, contact: 1, bite: 1 },
		shortDesc: "10% chance to make the target flinch.",
		target: "normal",
		type: "Dragon",
		secondary: {
			chance: 10,
			volatileStatus: 'flinch',
		},
	},
	astralbeam: {
		num: 111,
		accuracy: 100,
		basePower: 90,
		category: "Special",
		name: "Astral Beam",
		pp: 15,
		priority: 0,
		flags: { protect: 1, mirror: 1 },
		shortDesc: "10% chance to lower target's Sp. Def by 1.",
		target: "normal",
		type: "Arcane",
		secondary: {
			chance: 10,
			boosts: {
				spd: -1,
			},
		},
	},
	shadowburst: {
		num: 112,
		accuracy: 90,
		basePower: 130,
		category: "Special",
		name: "Shadow Burst",
		pp: 5,
		priority: 0,
		flags: { protect: 1, mirror: 1 },
		shortDesc: "Lowers the user's Sp. Atk by 2.",
		target: "normal",
		type: "Shadow",
		self: {
			boosts: {
				spa: -2,
			},
		},
	},
	divinewrath: {
		num: 113,
		accuracy: 100,
		basePower: 100,
		category: "Special",
		name: "Divine Wrath",
		pp: 10,
		priority: 0,
		flags: { protect: 1, mirror: 1 },
		shortDesc: "Ignores target's stat changes.",
		target: "normal",
		type: "Holy",
		ignoreEvasion: true,
		ignoreDefensive: true,
	},
	tidalwave: {
		num: 114,
		accuracy: 100,
		basePower: 95,
		category: "Special",
		name: "Tidal Wave",
		pp: 10,
		priority: 0,
		flags: { protect: 1, mirror: 1 },
		shortDesc: "Hits all adjacent foes.",
		target: "allAdjacentFoes",
		type: "Nature",
	},
	soulburn: {
		num: 115,
		accuracy: 100,
		basePower: 80,
		category: "Special",
		name: "Soul Burn",
		pp: 15,
		priority: 0,
		flags: { protect: 1, mirror: 1 },
		shortDesc: "30% chance to burn the target.",
		target: "normal",
		type: "Undead",
		secondary: {
			chance: 30,
			status: 'brn',
		},
	},
	dragonbreath: {
		num: 116,
		accuracy: 100,
		basePower: 60,
		category: "Special",
		name: "Dragon Breath",
		pp: 20,
		priority: 0,
		flags: { protect: 1, mirror: 1 },
		shortDesc: "30% chance to paralyze the target.",
		target: "normal",
		type: "Dragon",
		secondary: {
			chance: 30,
			status: 'par',
		},
	},
	naturepulse: {
		num: 117,
		accuracy: 100,
		basePower: 80,
		category: "Special",
		name: "Nature Pulse",
		pp: 20,
		priority: 0,
		flags: { protect: 1, mirror: 1, pulse: 1 },
		shortDesc: "Aura/Pulse move.",
		target: "normal",
		type: "Nature",
	},
	arcanestorm: {
		num: 118,
		accuracy: 70,
		basePower: 110,
		category: "Special",
		name: "Arcane Storm",
		pp: 10,
		priority: 0,
		flags: { protect: 1, mirror: 1 },
		shortDesc: "High power, low accuracy.",
		target: "normal",
		type: "Arcane",
	},
	holysmend: {
		num: 119,
		accuracy: true,
		basePower: 60,
		category: "Special",
		name: "Holy Smite",
		pp: 25,
		priority: 0,
		flags: { protect: 1, mirror: 1 },
		shortDesc: "This move does not check accuracy.",
		target: "normal",
		type: "Holy",
	},
	darkvoid: {
		num: 120,
		accuracy: 50,
		basePower: 0,
		category: "Status",
		name: "Dark Void",
		pp: 10,
		priority: 0,
		flags: { protect: 1, mirror: 1, reflectable: 1 },
		shortDesc: "Puts the target to sleep.",
		target: "normal",
		type: "Shadow",
		status: 'slp',
	},
	healinglight: {
		num: 121,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Healing Light",
		pp: 10,
		priority: 0,
		flags: { snatch: 1, heal: 1 },
		shortDesc: "Heals the user by 50% of its max HP.",
		target: "self",
		type: "Holy",
		heal: [1, 2],
	},
	dragondance: {
		num: 122,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Dragon Dance",
		pp: 20,
		priority: 0,
		flags: { snatch: 1, dance: 1 },
		shortDesc: "Raises the user's Attack and Speed by 1.",
		target: "self",
		type: "Dragon",
		boosts: {
			atk: 1,
			spe: 1,
		},
	},
	arcaneshield: {
		num: 123,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Arcane Shield",
		pp: 15,
		priority: 0,
		flags: { snatch: 1 },
		shortDesc: "Raises the user's Defense and Sp. Def by 1.",
		target: "self",
		type: "Arcane",
		boosts: {
			def: 1,
			spd: 1,
		},
	},
	naturegrowth: {
		num: 124,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Nature Growth",
		pp: 15,
		priority: 0,
		flags: { snatch: 1 },
		shortDesc: "Raises the user's Sp. Atk and Sp. Def by 1.",
		target: "self",
		type: "Nature",
		boosts: {
			spa: 1,
			spd: 1,
		},
	},
	shadowcloak: {
		num: 125,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Shadow Cloak",
		pp: 15,
		priority: 0,
		flags: { snatch: 1 },
		shortDesc: "Raises the user's Evasiveness by 1.",
		target: "self",
		type: "Shadow",
		boosts: {
			evasion: 1,
		},
	},
	undeadcurse: {
		num: 126,
		accuracy: 100,
		basePower: 0,
		category: "Status",
		name: "Undead Curse",
		pp: 10,
		priority: 0,
		flags: { authentic: 1 },
		shortDesc: "Curses target. -1/4 max HP per turn.",
		target: "normal",
		type: "Undead",
		volatileStatus: 'curse',
	},
	astraltrance: {
		num: 127,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Astral Trance",
		pp: 10,
		priority: 0,
		flags: { snatch: 1 },
		shortDesc: "Raises the user's Sp. Atk by 2.",
		target: "self",
		type: "Arcane",
		boosts: {
			spa: 2,
		},
	},
	holyward: {
		num: 128,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Holy Ward",
		pp: 10,
		priority: 4,
		flags: { },
		shortDesc: "Protects the user from all attacks this turn.",
		target: "self",
		type: "Holy",
		volatileStatus: 'protect',
	},
	naturesgrace: {
		num: 129,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Nature Grace",
		pp: 5,
		priority: 0,
		flags: { snatch: 1, heal: 1 },
		shortDesc: "Heals the entire team's status conditions.",
		target: "allyTeam",
		type: "Nature",
	},
	bloodpact: {
		num: 130,
		accuracy: true,
		basePower: 0,
		category: "Status",
		name: "Blood Pact",
		pp: 10,
		priority: 0,
		flags: { snatch: 1 },
		shortDesc: "Raises Atk/SpA by 2, lowers Def/SpD by 1.",
		target: "self",
		type: "Shadow",
		boosts: {
			atk: 2,
			spa: 2,
			def: -1,
			spd: -1,
		},
	},
`;

try {
	// Update Characters
	let charsStr = fs.readFileSync(CHARACTERS_FILE, 'utf8');
	if (!charsStr.includes('crimsonassassin')) {
		charsStr = charsStr.replace('};', newCharacters + '\\n};');
		fs.writeFileSync(CHARACTERS_FILE, charsStr);
		console.log('Characters updated.');
	} else {
		console.log('Characters already seeded.');
	}

	// Update Moves
	let movesStr = fs.readFileSync(MOVES_FILE, 'utf8');
	if (!movesStr.includes('crimsonblade')) {
		movesStr = movesStr.replace('};', newMovesStr + '\\n};');
		fs.writeFileSync(MOVES_FILE, movesStr);
		console.log('Moves updated.');
	} else {
		console.log('Moves already seeded.');
	}

	console.log('Seeding process complete.');
} catch (e) {
	console.error('Error seeding data:', e);
}
